import {chromium} from 'playwright';
import fs from 'node:fs';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:4173');await page.evaluate(()=>localStorage.clear());await page.reload();
await page.screenshot({path:'/tmp/benmp-home.png',fullPage:true});
await page.locator('[data-action="start"]').click();
await page.locator('#country').waitFor();
if(await page.locator('#country option').count()!==243)throw Error('Country list incomplete or restricted entries visible');
for(const code of ['CU','IR','KP','SY','RU','BY'])if(await page.locator(`#country option[value=\"${code}\"]`).count())throw Error(`Restricted country offered: ${code}`);
await page.locator('#amount').fill('234.56');await page.locator('#country').selectOption('KE');
await page.locator('#giving-form button[type="submit"]').click();
await page.locator('#name').fill('Demo Partner');await page.locator('#email').fill('demo@example.com');await page.locator('#phone').fill('0700000000');await page.locator('#giving-form button[type="submit"]').click();
if(!await page.getByText('M-PESA',{exact:true}).isVisible()||!await page.getByText('Airtel Money',{exact:true}).isVisible())throw Error('Kenya routing missing');
await page.screenshot({path:'/tmp/benmp-payment.png',fullPage:true});
await page.locator('#giving-form button[type="submit"]').click();await page.waitForURL('**/#result');
await page.getByText('Your generosity moves us.').waitFor();
const receiptDownload=page.waitForEvent('download');await page.locator('[data-action="receipt"]').click();const receipt=await receiptDownload;if(!receipt.suggestedFilename().endsWith('.pdf'))throw Error('Receipt is not a PDF');await receipt.saveAs('/tmp/benmp-receipt.pdf');
await page.locator('[data-action="dashboard"]').click();await page.waitForURL('**/#dashboard');
await page.locator('#signin').click();await page.locator('#login-entry').fill('anything');await page.locator('#login-form button[type="submit"]').click();await page.locator('[data-action="finish-login"]').click();
await page.getByRole('heading',{name:'Welcome, Joshua GBAFA'}).waitFor();
await page.goto('http://localhost:4173/#home');await page.locator('[data-action="partner"]').click();
await page.locator('[data-set="kind"][data-value="organization"]').click();await page.locator('#country').selectOption('US');await page.locator('#amount').fill('300');await page.locator('#giving-form button[type="submit"]').click();
await page.locator('#org').fill('Grace Outreach Church');await page.locator('#orgEmail').fill('finance@example.com');await page.locator('#address').fill('Demo address');await page.locator('[name="authorized"]').check();await page.locator('#giving-form button[type="submit"]').click();
await page.locator('[data-method="card"]').click();await page.locator('[name="mandate"]').check();await page.locator('#giving-form button[type="submit"]').click();await page.waitForURL('**/#result');
await page.locator('[data-action="dashboard"]').click();await page.locator('[data-tab="plans"]').click();await page.locator('[data-action="pause-plan"]').click();await page.locator('[data-action="resume-plan"]').click();await page.locator('[data-action="edit-plan"]').click();await page.locator('#plan-amount').fill('400');await page.locator('#plan-form button[type="submit"]').click();await page.locator('[data-action="run-plan"]').click();
await page.screenshot({path:'/tmp/benmp-dashboard.png',fullPage:true});
await page.locator('a[href="#messages"]').click();await page.locator('[data-action="compose"]').click();await page.locator('#message-channel').selectOption('WhatsApp');await page.locator('#compose-form button[type="submit"]').click();
await page.locator('[data-action="reply"]').first().click();await page.locator('#reply-body').fill('Thank you');await page.locator('#reply-form button[type="submit"]').click();
await page.reload();if(!await page.getByText('Your reply',{exact:true}).isVisible())throw Error('Persistence failed');
await page.locator('#appearance').click();if(!await page.locator('body').evaluate(b=>b.classList.contains('dark')))throw Error('Dark mode toggle failed');
await page.goto('http://localhost:4173/#give');await page.screenshot({path:'/tmp/benmp-dark.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.goto('http://localhost:4173/#home');await page.screenshot({path:'/tmp/benmp-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
await page.locator('#appearance').click();if(await page.locator('body').evaluate(b=>b.classList.contains('dark')))throw Error('Light mode toggle failed');
console.log(JSON.stringify({passed:['243 available countries; restricted countries omitted','custom amount','Kenya local methods','guest gift','permissive demo sign-in','organization monthly gift','pause/resume/edit/run monthly plan','message compose and reply','reload persistence','direct dark/light toggle and mobile layout'],errors}));
await browser.close();if(errors.length)process.exit(1);
