import {chromium} from 'playwright';
import fs from 'node:fs';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async value=>localStorage.setItem('qa-copied',value)},configurable:true}));
await page.goto('http://localhost:4173');await page.evaluate(()=>localStorage.clear());await page.reload();
if((await page.locator('.hero h1').innerText()).replace(/\n+/g,' ').trim()!=='Bring Salvation To The Multitudes')throw Error('Hero message is incorrect');
if(await page.locator('.hero h1 span').innerText()!=='Salvation')throw Error('Hero emphasis is incorrect');
if(await page.locator('.hero .eyebrow').innerText()!=='HOW CAN THEY HEAR WITHOUT A PREACHER?')throw Error('Hero supporting line is incorrect');
if(await page.locator('.hero .eyebrow').evaluate(el=>el.scrollWidth>el.clientWidth||getComputedStyle(el).whiteSpace!=='nowrap'))throw Error('Hero supporting line does not remain on one line');
if((await page.locator('.hero h1').evaluate(el=>getComputedStyle(el).textShadow))==='none')throw Error('Hero headline shadow is missing');
const favicon=await page.evaluate(async()=>{const img=new Image();img.src=document.querySelector('link[rel="icon"]').href;await img.decode();return [img.naturalWidth,img.naturalHeight]});if(favicon[0]!==favicon[1])throw Error('Favicon is not square');
await page.screenshot({path:'/tmp/benmp-home.png',fullPage:true});
await page.locator('[data-action="partner"]').click();
await page.getByRole('heading',{name:'Become a BENMP Partner'}).waitFor();
if(await page.locator('#email').count()!==1||await page.locator('#amount').count())throw Error('Partner flow does not start with registration');
if((await page.locator('.steps').innerText()).replace(/\s+/g,' ').trim().includes('Your details')===false)throw Error('Partner steps are missing');
await page.goto('http://localhost:4173/#home');await page.locator('[data-action="start"]').click();
await page.locator('#country-search').waitFor();
if(!await page.getByRole('heading',{name:'Give your donation',exact:true}).count()||await page.locator('.giving-layout > .panel > .section-title').count()||await page.getByText(/01 \/ 03|02 \/ 03|03 \/ 03/).count())throw Error('Donation heading or removed step counter is incorrect');
if(await page.locator('#amount').inputValue()!==''||await page.locator('#summary-amount').innerText()!=='—')throw Error('Amount should start empty');
if(JSON.stringify(await page.locator('[data-amount]').allTextContents())!==JSON.stringify(['10','25','50','100','200']))throw Error('Ghana quick amounts are incorrect');
const amountType=await page.evaluate(()=>{const input=getComputedStyle(document.querySelector('#amount')),preview=getComputedStyle(document.querySelector('#summary-amount'));return [input.fontFamily,input.fontSize,input.fontWeight,input.letterSpacing,preview.fontFamily,preview.fontSize,preview.fontWeight,preview.letterSpacing]});if(amountType.slice(0,4).join('|')!==amountType.slice(4).join('|'))throw Error('Preview amount typography does not match the amount field');
if(await page.locator('#country option').count()!==243)throw Error('Country list incomplete or restricted entries visible');
for(const code of ['CU','IR','KP','SY','RU','BY'])if(await page.locator(`#country option[value="${code}"]`).count())throw Error(`Restricted country offered: ${code}`);
await page.locator('#country-search').fill('CD');if(await page.locator('#country-search').inputValue()!=='CD')throw Error('Incomplete currency spelling selected a country');
await page.locator('#country-search').fill('CEDIS');if(await page.locator('#country').inputValue()!=='GH'||!/^🇬🇭 Ghana — GHS$/.test(await page.locator('#country-search').inputValue()))throw Error('Cedis did not resolve to Ghana');
await page.locator('#country-search').fill('So');
if(await page.locator('#country-search').inputValue()!=='So')throw Error('Ambiguous country search completed too early');
if(await page.locator('#country').inputValue()!=='GH')throw Error('Ambiguous country search changed the selected country');
await page.locator('#country-search').fill('South Africa');
if(await page.locator('#country').inputValue()!=='ZA')throw Error('Exact country name was not selected');
await page.locator('#country-search').fill('ZA');
if(await page.locator('#country-search').inputValue()!=='ZA')throw Error('Country code search completed before a country was chosen');
if(!await page.locator('#country-options option').filter({hasText:/^ZA · ZAR · South African Rand/}).count())throw Error('Country code does not find South Africa');
if(JSON.stringify(await page.locator('[data-amount]').allTextContents())!==JSON.stringify(['100','250','500','1,000','2,500']))throw Error('South Africa quick amounts are not scaled to ZAR');
await page.locator('#country-search').fill('Nigeria');if(JSON.stringify(await page.locator('[data-amount]').allTextContents())!==JSON.stringify(['1,000','2,500','5,000','10,000','25,000']))throw Error('Nigeria quick amounts are not scaled to NGN');
await page.locator('#amount').fill('234.56');await page.locator('#country-search').fill('Kenya');
await page.locator('#giving-form button[type="submit"]').click();
if(await page.locator('.phone-field > span').innerText()!=='+254')throw Error('Phone prefix did not follow the selected country');
await page.locator('#name').fill('Joshua GBAFA');await page.locator('#email').fill('joshua@example.com');await page.locator('#phone').fill('0700000000');await page.locator('#giving-form button[type="submit"]').click();
if(!await page.getByText('M-PESA',{exact:true}).isVisible()||!await page.getByText('Airtel Money',{exact:true}).isVisible())throw Error('Kenya routing missing');
if(JSON.stringify(await page.locator('#giving-form [data-method] strong').allTextContents())!==JSON.stringify(['Mobile Money','Debit / credit card','Pesalink']))throw Error('Bank transfer is not the final Kenya payment option');
if(await page.locator('.phone-field > span').innerText()!=='+254')throw Error('Mobile-money phone prefix did not follow the selected country');
await page.locator('[data-method="bank"]').click();
if(!await page.getByText('Bank transfer details',{exact:true}).isVisible()||await page.getByText('Demo transfer instructions',{exact:true}).count())throw Error('Practical bank details are missing');
if(await page.locator('.transfer-row').count()!==7)throw Error('Bank transfer details are incomplete');
await page.locator('.transfer-row').filter({hasText:'Account number'}).locator('.copy-button').click();
if(await page.evaluate(()=>localStorage.getItem('qa-copied'))!=='0001234567890')throw Error('Bank detail copy button failed');
await page.screenshot({path:'/tmp/benmp-payment.png',fullPage:true});
await page.locator('#giving-form button[type="submit"]').click();await page.waitForURL('**/#result');
await page.getByText('Your generosity moves us.').waitFor();
if(!await page.locator('.success-mark.status-success').count()||await page.locator('.success-mark').innerText()!=='✓')throw Error('Successful payment treatment is incorrect');
if(/interactive demo|simulation only|prototype|no real payments|no money/i.test(await page.locator('body').innerText()))throw Error('Presentation disclaimer is still visible');
const receiptDownload=page.waitForEvent('download');await page.locator('[data-action="receipt"]').click();const receipt=await receiptDownload;if(!receipt.suggestedFilename().endsWith('.pdf'))throw Error('Receipt is not a PDF');await receipt.saveAs('/tmp/benmp-receipt.pdf');
await page.locator('[data-action="dashboard"]').click();await page.waitForURL('**/#dashboard');
await page.locator('#signin').click();await page.locator('#login-entry').fill('anything');await page.locator('#login-form button[type="submit"]').click();await page.locator('[data-action="finish-login"]').click();
await page.getByRole('heading',{name:'Welcome, Joshua GBAFA'}).waitFor();
await page.goto('http://localhost:4173/#home');await page.locator('[data-action="partner"]').click();
await page.locator('[data-set="kind"][data-value="organization"]').click();await page.locator('#country-search').fill('United States');
if(await page.locator('[data-action="profile"], [data-identity], #amount').count())throw Error('Signed-in partner registration contains redundant saved-detail or pledge controls');
await page.locator('#org').fill('Grace Outreach Church');await page.locator('#orgEmail').fill('finance@example.com');await page.locator('#address').fill('Demo address');await page.locator('[name="authorized"]').check();await page.locator('#giving-form button[type="submit"]').click();
if(!await page.getByRole('heading',{name:'Your monthly pledge',exact:true}).isVisible()||!await page.locator('#amount').count())throw Error('Monthly pledge step did not follow registration');
await page.locator('#amount').fill('300');await page.locator('[name="partnerConfirm"]').check();await page.locator('#giving-form button[type="submit"]').click();
await page.locator('[data-method="card"]').click();
for(const id of ['cardNumber','cardName','cardExpiry','cardCvc','billingPostal'])if(!await page.locator('#'+id).count())throw Error(`Card field missing: ${id}`);
await page.locator('#cardNumber').fill('anything');await page.locator('#cardName').fill('Joshua GBAFA');await page.locator('#cardExpiry').fill('12 / 34');await page.locator('#cardCvc').fill('123');await page.locator('#billingPostal').fill('00000');
await page.locator('[name="mandate"]').check();await page.locator('#giving-form button[type="submit"]').click();await page.waitForURL('**/#result');
await page.locator('[data-action="dashboard"]').click();await page.locator('[data-tab="plans"]').click();await page.locator('[data-action="pause-plan"]').click();await page.locator('[data-action="resume-plan"]').click();await page.locator('[data-action="edit-plan"]').click();await page.locator('#plan-amount').fill('400');await page.locator('#plan-form button[type="submit"]').click();await page.locator('[data-action="run-plan"]').click();
await page.locator('[data-tab="history"]').click();
await page.locator('#statement-period').selectOption('all');await page.locator('#statement-email').fill('statements@example.com');
const statementDownload=page.waitForEvent('download');await page.locator('#statement-form button[value="download"]').click();const statement=await statementDownload;if(!statement.suggestedFilename().endsWith('.pdf'))throw Error('Statement is not a PDF');await statement.saveAs('/tmp/benmp-statement.pdf');
if(fs.readFileSync('/tmp/benmp-statement.pdf',{encoding:'utf8',flag:'r'}).slice(0,4)!=='%PDF')throw Error('Statement PDF is invalid');
await page.locator('#statement-form button[value="email"]').click();await page.getByText('Giving statement emailed to statements@example.com',{exact:true}).waitFor();
await page.screenshot({path:'/tmp/benmp-dashboard.png',fullPage:true});
await page.locator('a[href="#messages"]').click();await page.getByText('Your BENMP giving statement',{exact:true}).waitFor();
if(!await page.getByText('BENMP giving statement.pdf',{exact:false}).isVisible())throw Error('Emailed statement attachment is missing');
const attachmentDownload=page.waitForEvent('download');await page.locator('[data-action="statement-attachment"]').click();await attachmentDownload;
await page.locator('[data-action="compose"]').click();await page.locator('#message-channel').selectOption('WhatsApp');await page.locator('#compose-form button[type="submit"]').click();
await page.locator('[data-action="reply"]').first().click();await page.locator('#reply-body').fill('Thank you');await page.locator('#reply-form button[type="submit"]').click();
await page.reload();if(!await page.getByText('Your reply',{exact:true}).isVisible())throw Error('Persistence failed');
await page.locator('#appearance').click();if(!await page.locator('body').evaluate(b=>b.classList.contains('dark')))throw Error('Dark mode toggle failed');
await page.goto('http://localhost:4173/#give');await page.screenshot({path:'/tmp/benmp-dark.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.goto('http://localhost:4173/#home');await page.screenshot({path:'/tmp/benmp-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
await page.locator('#appearance').click();if(await page.locator('body').evaluate(b=>b.classList.contains('dark')))throw Error('Light mode toggle failed');
const appleContext=await browser.newContext({viewport:{width:1280,height:900}});const apple=await appleContext.newPage();apple.on('pageerror',e=>errors.push(e.message));await apple.goto('http://localhost:4173/#give');await apple.evaluate(()=>localStorage.clear());await apple.reload();await apple.locator('#country-search').fill('United States');await apple.locator('#amount').fill('100');await apple.locator('#giving-form button[type="submit"]').click();await apple.locator('#name').fill('Joshua GBAFA');await apple.locator('#email').fill('joshua@example.com');await apple.locator('#phone').fill('2025550100');await apple.locator('#giving-form button[type="submit"]').click();if(!await apple.locator('.apple-pay-button').count())throw Error('Apple Pay action is missing');await apple.locator('.apple-pay-button').click();await apple.waitForURL('**/#result');await apple.locator('.success-mark.status-success').waitFor();await appleContext.close();
console.log(JSON.stringify({passed:['three-line salvation hero with shadow','single-line uppercase hero supporting line','square circular favicon','empty default amount','currency-scaled amount shortcuts','matched amount typography','currency-name and spelling search','partner registration then monthly pledge flow','243 available countries; restricted countries omitted','searchable country picker without premature completion','country phone prefixes','practical copyable bank transfer details','editable card entry form','Apple Pay completion','bank transfer ordered last','successful result with status-ready colors','presentation copy has no caveats','guest donation','organization monthly donation','giving statement PDF download and email attachment','pause/resume/edit/run monthly plan','message compose and reply','reload persistence','direct dark/light toggle and mobile layout'],errors}));
await browser.close();if(errors.length)process.exit(1);
